### ISSUE TITLE
How can I solve this error

### ISSUE THREAD

**Issue by enzovr** [inlife/discord-global-mutual#1]
Error: Cannot find module 'r2'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Enzo\Desktop\discord-global-mutual-master\export.js:1:74)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
PS C:\Users\Enzo\Desktop\discord-global-mutual-master>

**Comment by inlife** [comment]
try installing the dependency via `npm install`
